import 'package:flutter/material.dart';

Widget defaultTextForm({
  required TextEditingController controller,
  TextInputType? type,
  FocusNode? focusNode,
  String? label,
  TextStyle? labelStyle,
  InputBorder? border,
  InputBorder? focusedBorder,
  InputBorder? enableBorder,
  Icon? prefix,
  IconData? suffix,
  ValueChanged<String>? onSubmit,
  FormFieldValidator<String>? validate,
  ValueChanged<String>? onChange,
  TextInputAction? textInputAction,
  bool isPassword = false,
  String? hint,
  int? maxLines,
  AutovalidateMode? autoValidateMode,
  Iterable<String>? autofillHints,
  suffixPressed,
  bool? filled,
  Color? fillColor,
  Color? suffixIconColor,
  Color? bgColor,
  double radius = 35.0,
}) =>
    Padding(
      padding: const EdgeInsets.only(left: 15.0, right: 15.0),
      child: TextFormField(
        controller: controller,
        keyboardType: type,
        focusNode: focusNode,
        validator: validate,
        obscureText: isPassword,
        onChanged: onChange,
        onFieldSubmitted: onSubmit,
        maxLines: maxLines,
        autovalidateMode: autoValidateMode,
        enableSuggestions: true,
        autofillHints: autofillHints,
        textInputAction: textInputAction,
        decoration: InputDecoration(
          filled: filled,
          fillColor: fillColor,
          hintText: hint,
          labelText: label,
          labelStyle: labelStyle,
          prefixIcon: prefix,
          suffixIcon: IconButton(
            icon: Icon(
              suffix,
              color: suffixIconColor,
            ),
            onPressed: suffixPressed,
          ),
          enabledBorder: enableBorder,
          focusedBorder: focusedBorder,
          border: border,
        ),
      ),
    );
